### ISSUE TITLE
printf and vprintf do not conform to their C/C++ counterparts

### ISSUE THREAD

**Issue by asferreira** [fienestar/printf-ts#1]
Hello,

Using printf-ts I notice that printf and vprintf add a newline '\n' at the end of the string, what the original ones don't do. I think it is probably related to the use of 'console.log' to output the string.
It is just a minor detail, but it would be nice if them behave the same way C functions do.

Best regards,

Anderson

**Comment by fienestar** [comment]
Thanks for the suggestion @asferreira! I'll fix it to use process.stdout.write if it exists
